
spring:
  application:
    name: lab3
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/lab3_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
     init:
      mode: always
server:
  port: 8080
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-.....okta.com/oauth2/default



